spring:
  application:
    name: gateway-server
  security:
    jwt:
      key:
        abcdefg
      access-token-expire:
        15
      refresh-token-expire:
        7
      temporarilyExpire: # 没有点击记住我的长token过期时间，单位小时
        3
server:
  port: 8090
