server:
  port: 8090
  ssl:
    enabled: true
    key-store: classpath:cert/localhost.p12
    key-store-type: PKCS12
    key-store-password: 123456
    key-alias: selfsign

spring:
  application:
    name: gateway-server
