server:
  port: 8090
  ssl:
    enabled: true
    key-store: classpath:cert/localhost.p12
    key-store-type: PKCS12
    key-store-password: 123456
    key-alias: selfsign

my:
  gateway:
    whitelist:
      - /api/auth/login
      - /api/auth/logout
      - /api/auth/refreshVerify
      - /api/user/getUserAvatar
      - /api/playlist/getPlaylistAvatar
      - /api/song/getSongAvatar
      - /api/singer/getSingerAvatar

spring:
  application:
    name: backstage-gateway-server
  security:
    jwt:
      key:
        abcdefg

  data:
    redis:
      host: localhost
      port: 6379
      database: 0

  cloud:
    nacos:
      discovery:
        server-addr: http://127.0.0.1:8848
        enabled: true
      config:
        server-addr: localhost:8848
        file-extension: yaml
        group: DEFAULT_GROUP
        namespace: public
        refresh-enabled: true
    gateway:
      httpclient:
        ssl:
          use-insecure-trust-manager: true
      routes:
        - id: auth-server
          uri: lb://backstage-auth-server   # 认证服务的服务名
          predicates:
            - Path=/api/auth/**     # 匹配 /api/auth/** 的所有请求
        - id: user-server
          uri: lb://backstage-user-server   # 用户服务的服务名
          predicates:
            - Path=/api/user/**     # 匹配 /api/user/** 的所有请求
        - id: playlist-server
          uri: lb://backstage-playlist-server   # 播放列表服务的服务名
          predicates:
            - Path=/api/playlist/**     # 匹配 /api/playlist/** 的所有请求
        - id: song-server
          uri: lb://backstage-song-server   # 歌曲服务的服务名
          predicates:
            - Path=/api/song/**     # 匹配 /api/song/** 的所有请求
        - id: singer-server
          uri: lb://backstage-singer-server   # 歌手服务的服务名
          predicates:
              - Path=/api/singer/**     # 匹配 /api/singer/** 的所有请求
