server:
  port: 9002
  ssl:
    enabled: true
    key-store: classpath:cert/localhost.p12
    key-store-type: PKCS12
    key-store-password: 123456
    key-alias: selfsign

spring:
  application:
    name: backstage-user-server

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8  # Set to your timezone

  cloud:
    nacos:
      discovery:
        server-addr: http://127.0.0.1:8848
        secure: true
        metadata:
          secure: true
      config:
        server-addr: localhost:8848
        file-extension: yaml
        group: DEFAULT_GROUP
        namespace: public
        refresh-enabled: true

  datasource:
    url: jdbc:mysql://localhost:3306/mc-user
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB


seata:
  enabled: true
  application-id: ${spring.application.name}
  tx-service-group: default_tx_group
  config:
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8848
      namespace: ""
      group: SEATA_GROUP
#      username: nacos
#      password: nacos
      # 使用动态命名
      data-id: seata-${spring.application.name}.properties
  registry:
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8848
      group: SEATA_GROUP
      namespace: ""
#      username: nacos
#      password: nacos
      application: seata-server
